### PR TITLE
Task/english edits

### LINKED ISSUE #533: Change to https://claim-tax-benefits.azurewebsites.net/personal/name
Please change "doesn't" to "does not"

Thanks!

### LINKED ISSUE #534: Change to https://claim-tax-benefits.azurewebsites.net/offramp/address
Please change "can't" to "cannot"

Thanks!

### LINKED ISSUE #535: Change to https://claim-tax-benefits.azurewebsites.net/offramp/maritalStatus
Please change "can't" to "cannot"

Thanks!

### LINKED ISSUE #536: Change to https://claim-tax-benefits.azurewebsites.net/trillium/propertyTax/amount
In header, please change "taxes" to "tax"

In the drop down menu, please add a period after "taxes"

Thanks!

### LINKED ISSUE #538: Change to https://claim-tax-benefits.azurewebsites.net/confirmation
For Ontario Trillium Benefit in the drop down menu

- please remove the word "government" from the middle column

-please change the last column to "paid monthly if $360 or more **or** paid yearly if less than $360"

Thanks!

### PR DESCRIPTION
**Pull request by katedee**
## `/personal/name`
- Resolves #533
localhost_3005_personal_name

## `/offramp/address`
- Resolves #534
localhost_3005_offramp_address

## `/offramp/maritalStatus`
- Resolves #535
localhost_3005_offramp_maritalStatus

## `/trillium/propertyTax/amount`
- Resolves #536 
localhost_3005_trillium_propertyTax_amount

## `/confirmation`
- Resolves #538
localhost_3005_confirmation_lang=en (1)

### CODE REVIEW

**Comment by katedee** [comment]
Hey @YedidaZalik based on how we're currently generating the table, it does pose a bit of code changing. Happy to take it on though :)

Unless, @pcraig3 can you think of an easy way to get that second _or_ on it's own line at least? I tried a couple things to no avail!

**Comment by katedee** [comment]
Oooh I could run a check for that particular cell and then break up the text accordingly. What do y'all think?

**Comment by YedidaZalik** [comment]
It's okay if this can't be done.
If the "or" cannot be bolded, then even if could be on a separate line without having to do a lot of work, that would be great. But if that is going to take up a lot of work, then I would say we can let this one go :)

**Comment by katedee** [comment]
@YedidaZalik Alright let's let it go for now for the sake of getting it in for a general content review (because who knows! maybe we'll change the line!)

**Comment by katedee** [comment]
@YedidaZalik Actually, I'm going to run a check on the cell and make those changes. Will be up either by lunch or shortly after :D

**Comment by katedee** [comment]
Aaaand updated! I don't know why I thought it would be so complicated 🤦‍♀ 
Blame it on the poor sleep

**Pull request merged**
