### PR TITLE
Content changes for confirmation page

### LINKED ISSUE #340: Changes to https://claim-tax-benefits.azurewebsites.net/confirmation
Please add blue banner similar to Lite version for filing code

**Please replace:**
You will get a notice of reassessment if CRA makes any changes.

If CRA owes you money, then:

CRA will put the money in your bank account if you arranged direct deposit.
your cheque comes in the mail if you didn’t arrange direct deposit.
Thank you for using our service. Please share your feedback.

**With:**
If CRA owes you money, then:
									
• CRA will put it in your bank account if you registered for direct deposit 
• your cheque comes with the notice if you did not register for direct deposit.
									
Thank you for using the Claim Tax Benefits service. Please share your feedback to improve this service.  [hyperlink under "share your feedback"]
								
____________________
**[French] Please replace:**
Vous recevrez un avis de nouvelle cotisation si l’ARC apporte des modifications.

Si l’ARC vous doit de l’argent, alors : 

• l’ARC déposera l’argent dans votre compte bancaire si vous êtes inscrit au dépôt direct.
• vous recevrez un chèque par la poste si vous n’êtes pas inscrit au dépôt direct.

Merci d’avoir utilisé notre service. Faites-nous part de vos commentaires.

**With:**
Si l’ARC vous doit de l’argent, alors : 

• l’ARC déposera l’argent dans votre compte bancaire si vous êtes inscrit au dépôt direct.
• vous recevrez un chèque en même temps que votre avis si vous n’êtes pas inscrit au dépôt direct.

Merci d’avoir utilisé le service _Réclamer des avantages fiscaux_. N’hésitez pas à envoyer vos commentaires pour aider à l’améliorer. [hyperlink under "envoyer vos commentaires"]

### PR DESCRIPTION
**Pull request by brdunfield**
The content half of #340 

The banner will be done as a separate PR.

### CODE REVIEW

**Comment by pcraig3** [comment]
Hi @brdunfield!

The banner we're looking for looks like the one [on the start page](https://claim-tax-benefits.azurewebsites.net/start). [Some example code is in the template file](https://github.com/cds-snc/cra-claim-tax-benefits/blob/master/views/start/index.pug#L8) (ignore that we're using keys instead of the actual words, we're not doing that on other pages).

**Comment by brdunfield** [comment]
@YedidaZalik Could you confirm if this is how you wanted the blue banner added?

**Comment by YedidaZalik** [comment]
@brdunfield This looks great to me, but it was actually @brianhendrick1 or @nmakuch  who suggested the banner revision and I just included it in the github issue, so probably one of them should take a look :)

**Comment by YedidaZalik** [comment]
Oops @brdunfield sorry I missed that "You will get a notice of reassessment if CRA makes any changes." should be deleted.

**Comment by brianhendrick1** [comment]
Example of banner attached in comment and is in this [trello card](https://trello.com/c/i1twNn0Q/371-updates-to-confirmation-page)
Screen Shot 2019-11-04 at 12 23 24 PM

**Pull request merged**
